### ISSUE TITLE
Add pages link next to github description

### ISSUE THREAD

**Issue by jedireza** [mozilla/fxemoji#1]
Let's add the GitHub pages link so it's easy for people to see the emojis :wink: 

http://mozilla.github.io/fxemoji/

![screen shot 2015-06-29 at 1 42 19 pm](https://cloud.githubusercontent.com/assets/979929/8417941/b1eba9ea-1e64-11e5-9338-57a17ebb1cab.png)

**Comment by pivanov** [comment]
Thanks :) it's done
