### ISSUE TITLE
The black and white glyphs are unusable

### ISSUE THREAD

**Issue by khaledhosny** [mozilla/fxemoji#11]
On systems where the colour tables are unsupported the default glyphs will be used in black and white, but they seem to automatically generated from the coloured SVGs and end up mostly as black blobs making them unusable. I’m not sure if there is an easy way to handle this without having to draw a separate black and white version for each glyph.

**Comment by pivanov** [comment]
Yep. We need to have BW version of the icons if we want to have BW version. It's not easy to generate them automatically

**Comment by floatingatoll** [comment]
Staffing has been withdrawn for this project, so no further improvements will occur. Closing with our sincerest apologies for the delay in responding.
