### ISSUE TITLE
UK flag is a poor representation

### ISSUE THREAD

**Issue by johndrinkwater** [mozilla/fxemoji#13]
I can appreciate that FirefoxOS’ Unicode flags want to fit somewhat into the levity of Emoji, yet the colours for this flag are insultingly wide of the mark, and the red saltire is completely lacking it’s counterchange (the white always follows the red clockwise). It makes this a different flag entirely.

https://upload.wikimedia.org/wikipedia/commons/d/d8/United_Kingdom_Flag_Specifications.svg
should give an indication of how the offsets ought to be as a ratio of the design.

As such, greatbritainflag.*.svg need a rework - does this repo take PRs?

**Comment by floatingatoll** [comment]
Staffing has been withdrawn for this project, so no further improvements will occur. Closing with our sincerest apologies for the delay in responding.
