### ISSUE TITLE
Update the emoji set Unicode to 8.0

### ISSUE THREAD

**Issue by pradyunsg** [mozilla/fxemoji#14]
While the roadmap does mention the plan to update the emoji set Unicode to 8.0 by the end of 2016 Q1, it hasn't happened yet. I would just like to enquire what is the status on this?

Also, why Emoji One is not used? I'm not saying don't have your own set of emojis, just asking as to why an existing (and complete [[1](http://unicode.org/emoji/charts/full-emoji-list.html)]) emoji has not been used...

**Comment by fitojb** [comment]
Well, Firefox OS as a mobile device platform is no more (they pivoted towards IoT), so it shouldn’t come as a surprise that this repository is getting stale.

**Comment by jobukkit** [comment]
Surely Panasonic's TV's need to be able to display emoji's in the browser?

**Comment by pradyunsg** [comment]
This repo has been inactive for a while now. Closing this.
