### ISSUE TITLE
U+1F4C9 CHART WITH DOWNWARDS TREND has impossible line

### ISSUE THREAD

**Issue by salty-horse** [mozilla/fxemoji#15]
The line graph depicted on U+1F4C9 has 3 segments. The second segment is a line that goes backwards on the X axis. This is wrong, and should be corrected.

It is common for the X axis in such charts to represent time. The points should always go from a lower X value to a higher X value.

**Comment by floatingatoll** [comment]
Staffing has been withdrawn for this project, so no further improvements will occur. Closing with our sincerest apologies for the delay in responding.
