### ISSUE TITLE
Horrible presentation of all Japanese seasonal related event emojis/character emojis

### ISSUE THREAD

**Issue by ringmasters** [mozilla/fxemoji#16]
Hey guys,

I am quite sure that all these emojis weren't "proofread" by any native Japanese designers, but I find all those kanji character emojis hyper-disproportional from designer's perspective(it's really distorted), as well as orientalism from those Japanese seasonal events as displayed. I can't tell what these emojis represent.

I'll be specific. 

Japanese disportional letterings
🈁 Japanese “here” Button
🈂️ Japanese “service Charge” Button
🈷️ Japanese “monthly Amount” Button
🈶 Japanese “not Free of Charge” Button
🈯 Japanese “reserved” Button
🉐 Japanese “bargain” Button
🈹 Japanese “discount” Button
🈚 Japanese “free of Charge” Button
🈲 Japanese “prohibited” Button
🉑 Japanese “acceptable” Button
🈸 Japanese “application” Button
🈴 Japanese “passing Grade” Button
🈳 Japanese “vacancy” Button
㊗️ Japanese “congratulations” Button
㊙️ Japanese “secret” Button
🈺 Japanese “open for Business” Button
🈵 Japanese “no Vacancy” Button

Japanese specific event emojis
Hinamatsuri Dolls
http://emojipedia.org/japanese-dolls/
Moon Viewing
http://emojipedia.org/moon-viewing-ceremony/

Please rework on these for the next update. Thank you.

**Comment by jobukkit** [comment]
Assuming there will be another update 😟 Everything Firefox OS related, even things like this that could have been reused in the browser, has been completely killed off for no reason.

**Comment by floatingatoll** [comment]
Staffing has been withdrawn for this project, so no further improvements will occur. Closing with our sincerest apologies for the delay in responding.
