### ISSUE TITLE
Do Not Litter Symbol doesn’t contain the right icon and isn’t crossed out

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/fxemoji#2]
![donotlittersymbol-fxemoji](https://cloud.githubusercontent.com/assets/51007/8768214/f1f30ea8-2ecb-11e5-8be6-af486fd08bf1.PNG)

Name: donotlittersymbol
Codepoint: 1F6AF

The icon should be of a person littering, rather than a waterspout. The red circle outline should also be crossed out.

**Comment by patrykdesign** [comment]
@pivanov bram is right, if the correct icon doesn't exist, I am sure @amyylee can help you out.

**Comment by AmyYLee** [comment]
Hi, 
I just provided the correct icon to @pivanov so he should be able to fix this issue.

**Comment by AmyYLee** [comment]
@pivanov Can you please close this bug once the emoji has been replaced? Thanks!

**Comment by pivanov** [comment]
Sure,
work on it :)

**Comment by pivanov** [comment]
http://mozilla.github.io/fxemoji/dist/symbols/index.html
I think is fixed now :)

**Comment by AmyYLee** [comment]
@pivanov Thanks!
