### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nclm** [mozilla/fxemoji#3]
Hi,
This new emoji font is great news! I also like the visual design.
What is the license for the emoji drawings and for the code generating the font?

**Comment by patrykdesign** [comment]
Just updated the license file @nclm 
Basically its apache 2.0 for code, CC BY for graphics.

**Comment by nclm** [comment]
Great, thanks :)

**Comment by ebraminio** [comment]
Is CCby _4.0_ OK? I've uploaded them [here](https://commons.wikimedia.org/wiki/Category:Firefox_OS_Emoji) ([see our collection also](https://commons.wikimedia.org/wiki/Emoji), which is mainly for Wikipedia use) and am eager to see other Emojis also :)

BTW, nice to see your here Nicolas :)

**Comment by patrykdesign** [comment]
@ebraminio it should be. We are going to be doing some updates to the emojis in the next few weeks, so would be good to monitor this repo.

**Comment by floatingatoll** [comment]
Could you please add a LICENSE top-level with guidelines for how the repo is licensed?

**Comment by patrykdesign** [comment]
@floatingatoll it should be there: https://github.com/mozilla/fxemoji/blob/master/LICENSE.md
