### ISSUE TITLE
Create bundled all-in-one TTF release?

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/fxemoji#6]
It is really hard to get Emoji working on Ubuntu (and likely other Linux distributions).
The most popular guides found by search engines contain either invalid steps (http://www.omgubuntu.co.uk/2014/11/see-install-use-emoji-symbols-ubuntu-linux did not work here) or link to font files that do not exist any more and might be problematic from a license perspective (see https://gist.github.com/robotslave/4633393).

For this reason, I wonder if it makes sense to create a bundled release of the fxemoji font and offer it for download so Linux users can benefit from the font. It's really great that we've done this for Firefox OS and that there's a permissive license too.

What do you think @pivanov?

**Comment by april** [comment]
These sort of pre-patched fonts are not uncommon on OS X, such as with the Powerline patched fonts that are used for doing all sorts of nifty things in terminals:

https://github.com/powerline/fonts

(repo includes a font patcher and everything)

**Comment by floatingatoll** [comment]
Staffing has been withdrawn for this project, so no further improvements will occur. Closing with our sincerest apologies for the delay in responding.
